version: '2.1'

services:
  puppeteer:
    image: linuxserver/chromium:latest
    container_name: puppeteer
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - PROXY_URL=warp_proxy
      - CRAWL_URL=https://www.nhatot.com/mua-ban-dat?f=p&page=
    ports:
      - 3000:3000
    shm_size: '2gb'