services:
  node_de:
    image: node:alpine
    container_name: node_de
    restart: always
    entrypoint:
      - sleep
      - infinity
    network_mode: bridge
    volumes:
      - node_latest:/root

volumes:
  node_latest:
    name: node_latest